version: "3"

services:
  chuymysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=d4a1234
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

  chuyphp:
    image: tmmxcheck/mentoring:php54 
    volumes:
      - ./code/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:
      - chuymysql
